import { TranslationMessages } from 'react-shop-types';

const englishMessages: TranslationMessages = {
  rs: {
    action: {
      accept: 'Accept',
      add: 'Add New',
      back: 'Go Back',
      cancel: 'Cancel',
      checkout: 'Checkout',
      clear_input_value: 'Clear value',
      close: 'Close',
      confirm: 'Confirm',
      continue: 'Continue Shopping',
      create: 'Create',
      decline: 'Decline',
      decrease: 'Decrease',
      delete: 'Delete',
      deselect: 'Deselect',
      edit: 'Edit',
      increase: 'Increase',
      move_down: 'Move down',
      move_up: 'Move up',
      open: 'Open',
      refresh: 'Refresh',
      remove: 'Remove',
      save: 'Save',
      search: 'Search',
      select: 'Select',
      selectAll: 'Select All',
      sort: 'Sort By',
      start: 'Start Shopping',
      switch: 'Switch to',
      unselect: 'Unselect',
      update: 'Update',
    },
    auth: {
      account: 'Account',
      auth_check_error: 'Please login to continue',
      forgot_password: 'Forgot Your Password?',
      login: 'Login',
      logout: 'Logout',
      profile: 'Profile',
      reset_password: 'Reset password',
      sign_in: 'Sign In',
      sign_up: 'Sign Up',
    },
    boolean: {
      yes: 'Yes',
      no: 'No',
    },
    cart: {
      add: 'Add to Cart',
      added: 'Added to cart',
      clear: 'Clear Cart',
      confirm: 'Do you want clear the shopping cart?',
      empty: 'Your shopping cart is empty',
      inside: 'In the cart',
      link: 'Go to Cart',
      open: 'Open Cart',
      remove: 'Remove from cart',
      title: 'Cart',
    },
    checkout: {
      customer: 'Customer',
      delivery: 'Delivery',
      shipping: 'Shipping address',
      link: 'Checkout Now',
      payment: 'Payment',
      review: 'Review',
      title: 'Checkout',
    },
    field: {
      address: 'Address',
      cardNumber: 'Card Number',
      city: 'City',
      company: 'Company',
      confirm_password: 'Confirm password',
      country: 'Country',
      email: 'Email',
      expirationDate: 'Expiration Date',
      firstName: 'First Name',
      fullName: 'Full Name',
      lastName: 'Last Name',
      name: 'Name',
      password: 'Password',
      phone: 'Phone',
      province: 'Province',
      postalCode: 'Postal Code',
      username: 'Username',
    },
    message: {
      created: 'Element created',
      data_provider_error: 'dataProvider error. Check the console for details.',
      empty: 'No results found',
      error: 'Something went wrong',
      http_error: 'Server communication error',
      invalid_form: 'The form is not valid. Please check for errors',
      item_doesnt_exist: 'Item does not exist',
      not_found: 'Either you typed a wrong URL, or you followed a bad link',
      unsaved_changes: "Some of your changes weren't saved. Are you sure you want to ignore them?",
      updated: '{element} updated',
    },
    navigation: {
      back: 'Go back',
      drawer: 'Open Drawer',
      no_results_found: 'No results found',
      show: 'Show',
      next: 'Next',
      previous: 'Previous',
    },
    product: {
      author: 'author',
      category: 'Category',
      description: 'Description',
      discount: 'Discount',
      image: 'Image',
      inStock: 'In Stock',
      outStock: 'Out of stock',
      unavailable: 'Unavailable',
      items: '{count, plural, =0 {No items} =1 {1 item} other {# items}}',
      name: 'Name',
      payment: 'Payment',
      price: 'Price',
      quantity: 'Quantity',
      rating: 'Rating',
      total: 'Total',
    },
    sort: {
      ASC: 'ascending',
      DESC: 'descending',
      default: 'Default',
      hignToLow: 'Price: High to Low',
      lowToHigh: 'Price: Low to High',
      rating: 'Rating',
      top: 'Top Sellers',
    },
    validation: {
      email: 'Must be a valid email',
      maxLength: 'Must be {max} characters or less',
      maxValue: 'Must be {max} or less',
      minLength: 'Must be {min} characters at least',
      minValue: 'Must be at least {min}',
      number: 'Must be a number',
      oneOf: 'Must be one of: {options}',
      regex: 'Must match a specific format (regexp): {pattern}',
      required: 'Required',
      unique: 'Must be unique',
    },
    view: {
      dark: 'Dark',
      grid: 'Grid',
      light: 'Light',
      list: 'List',
      switch: 'Switch to {mode} theme',
      title: 'View',
    },
  },
  pages: {
    home: 'Home',
    contacts: 'Contacts',
    not_found: 'Not found',
  },
};

export default englishMessages;
