export type SignInPageErrorParam =
  | 'Signin'
  | 'OAuthSignin'
  | 'OAuthCallbackError'
  | 'OAuthCreateAccount'
  | 'EmailCreateAccount'
  | 'Callback'
  | 'OAuthAccountNotLinked'
  | 'EmailSignin'
  | 'CredentialsSignin'
  | 'SessionRequired';

export type BuiltInProviderType =
  | RedirectableProviderType
  | OAuthProviderType
  | WebAuthnProviderType;

export type WebAuthnProviderType = 'webauthn';

export type AuthProviderType =
  | 'oidc'
  | 'oauth'
  | 'nodemailer'
  | 'credentials'
  | WebAuthnProviderType;

export type RedirectableProviderType = 'nodemailer' | 'credentials';

export type OAuthProviderType =
  | '42-school'
  | 'apple'
  | 'asgardeo'
  | 'atlassian'
  | 'auth0'
  | 'authentik'
  | 'azure-ad-b2c'
  | 'azure-ad'
  | 'azure-devops'
  | 'battlenet'
  | 'beyondidentity'
  | 'box'
  | 'boxyhq-saml'
  | 'bungie'
  | 'click-up'
  | 'cognito'
  | 'coinbase'
  | 'descope'
  | 'discord'
  | 'dribbble'
  | 'dropbox'
  | 'duende-identity-server6'
  | 'eveonline'
  | 'facebook'
  | 'faceit'
  | 'foursquare'
  | 'freshbooks'
  | 'fusionauth'
  | 'github'
  | 'gitlab'
  | 'google'
  | 'hubspot'
  | 'identity-server4'
  | 'instagram'
  | 'kakao'
  | 'keycloak'
  | 'line'
  | 'linkedin'
  | 'mailchimp'
  | 'mastodon'
  | 'mattermost'
  | 'medium'
  | 'naver'
  | 'netlify'
  | 'nodemailer'
  | 'notion'
  | 'okta'
  | 'onelogin'
  | 'ory-hydra'
  | 'osso'
  | 'osu'
  | 'passage'
  | 'passkey'
  | 'patreon'
  | 'pinterest'
  | 'pipedrive'
  | 'reddit'
  | 'resend'
  | 'salesforce'
  | 'sendgrid'
  | 'slack'
  | 'spotify'
  | 'strava'
  | 'todoist'
  | 'trakt'
  | 'twitch'
  | 'twitter'
  | 'united-effects'
  | 'webauthn'
  | 'wikimedia'
  | 'wordpress'
  | 'workos'
  | 'zitadel'
  | 'zoho'
  | 'zoom';
