name: Pull Request
on:
  push:
    branches: [next, main]
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    name: commit-lint
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v5
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: USE Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false
      - name: Lint
        run: pnpm run lint
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: USE Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false
      - name: Unit Tests
        run: pnpm test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: USE Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false
      - name: Build
        run: pnpm run build
      - name: Zip packages build artifact
        run: zip build.zip -r examples/shop-data-generator/dist packages/*/dist
      - name: Upload packages build artifact
        uses: actions/upload-artifact@v4
        with:
          name: packages-build
          path: build.zip
          retention-days: 1
  demo:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: USE Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false
      - name: Download packages build artifact
        uses: actions/download-artifact@v4
        with:
          name: packages-build
      - name: Unzip packages build artifact
        run: unzip -o -u build.zip
      - name: build demo
        run: pnpm run build-demo
        env:
          CI: true
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
